In [12]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [13]:
df = pd.read_csv('data/data_cleaned.csv')

In [14]:
df.head()

,Product ID,Height (cm),Width (cm),Depth (cm),Avg Daily Demand,Product Category
0,P20106,35.436002,22.622569,33.657885,49.123508,Electronics
1,P41070,28.556396,24.461528,44.912779,16.094638,Electronics
2,P29033,28.387143,16.138052,18.433578,17.235752,Food
3,P47714,23.283766,24.277033,26.857256,6.472163,Clothing
4,P14692,9.607678,23.973594,37.116032,15.737616,Food

In [15]:
numerical_features = ['Height (cm)', 'Width (cm)', 'Depth (cm)', 'Avg Daily Demand']
X = df[numerical_features]

In [16]:
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

In [17]:
df_scaled = df.copy()
df_scaled[numerical_features] = X_scaled

In [18]:
df_scaled.head()

,Product ID,Height (cm),Width (cm),Depth (cm),Avg Daily Demand,Product Category
0,P20106,0.521312,0.481925,0.635065,0.260515,Electronics
1,P41070,0.426555,0.515020,0.835129,0.085344,Electronics
2,P29033,0.424224,0.365226,0.364442,0.091396,Food
3,P47714,0.353932,0.511700,0.514179,0.034310,Clothing
4,P14692,0.165563,0.506239,0.696536,0.083450,Food

In [19]:
df_scaled.to_csv('data/feature_scaled.csv', index=False)

**Label Encoding**

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()


df_scaled['Product_Label'] = le.fit_transform(df_scaled['Product Category'])

In [9]:
df_scaled.head()

,Product ID,Height (cm),Width (cm),Depth (cm),Avg Daily Demand,Product Category,Product_Label
0,P20106,0.521312,0.481925,0.635065,0.260515,Electronics,1
1,P41070,0.426555,0.515020,0.835129,0.085344,Electronics,1
2,P29033,0.424224,0.365226,0.364442,0.091396,Food,2
3,P47714,0.353932,0.511700,0.514179,0.034310,Clothing,0
4,P14692,0.165563,0.506239,0.696536,0.083450,Food,2

In [10]:
from sklearn.preprocessing import OneHotEncoder

# Create OneHotEncoder object
encoder = OneHotEncoder(sparse_output=False)

# Apply One-Hot Encoding
encoded_data = encoder.fit_transform(df_scaled[['Product Category']])

# Create DataFrame for encoded columns
encoded_df = pd.DataFrame(
    encoded_data,
    columns=encoder.get_feature_names_out(['Product Category'])
)

# Concatenate with original dataframe
df_scaled = pd.concat([df_scaled, encoded_df], axis=1)

# Drop original categorical column
df_scaled.drop('Product Category', axis=1, inplace=True)

# Display result
print(df_scaled.head())

  Product ID  Height (cm)  Width (cm)  Depth (cm)  Avg Daily Demand  \
0     P20106     0.521312    0.481925    0.635065          0.260515
1     P41070     0.426555    0.515020    0.835129          0.085344
2     P29033     0.424224    0.365226    0.364442          0.091396
3     P47714     0.353932    0.511700    0.514179          0.034310
4     P14692     0.165563    0.506239    0.696536          0.083450

   Product_Label  Product Category_Clothing  Product Category_Electronics  \
0              1                        0.0                           1.0
1              1                        0.0                           1.0
2              2                        0.0                           0.0
3              0                        1.0                           0.0
4              2                        0.0                           0.0

   Product Category_Food  Product Category_Furniture  Product Category_Toys
0                    0.0                         0.0                    0.0
1                    0.0                         0.0                    0.0
2                    1.0                         0.0                    0.0
3                    0.0                         0.0                    0.0
4                    1.0                         0.0                    0.0

In [11]:
df_scaled.to_csv('data/feature_scaled.csv', index=False)